feat: add Makefile rules

diff --git a/utils/graphic/Makefile b/utils/graphic/Makefile
--- a/utils/graphic/Makefile
+++ b/utils/graphic/Makefile
@@ -26,18 +26,28 @@ NAME		=		libgraphic.a
 
 HEADER	=	libgraphic.h
 
+UT_SRC =
+
+UT_NAME	=	my_tests
+
+UT_FLAGS	=	--coverage -lcriterion
+
 all:		$(NAME)
 
 $(NAME):	$(OBJ)
-		$(AR) rc $(NAME) $(OBJ)
-		cp $(NAME) ../
-		cp $(HEADER) ../../include/
+	$(AR) rc $(NAME) $(OBJ)
+	cp $(NAME) ../
+	cp $(HEADER) ../../include/
+#	@ranlib $(LIB_NAME)
 
 clean:
 	$(RM) $(OBJ)
+	@find -name "*~" -delete -o -name "#*#" -delete
+	@find -name "*.gcda" -delete -o -name "*.gcno" -delete
 
 fclean: clean
-	$(RM) -f $(NAME) ../$(NAME)
+	$(RM) -f $(NAME) ../$(NAME) $(UT_NAME)
+	@find -name "coding-style-reports.log" -delete
 
 re:	fclean all
 
@@ -48,21 +58,29 @@ debug_comp:		$(OBJ)
 debug:	debug_comp clean
 
 tests_run:
-	@echo "Hello, we are happy to say that we didn't have any tests"
-#	@mkdir -p tests
-#	@if [ ! -f tests/*.c ]; then \
-#		echo "Error: tests/*.c not found"; \
-#		exit 1; \
-#	fi
-#	@gcc -o unit_tests $(SRC) tests/*.c --coverage -lcriterion -Iinclude
-#	./unit_tests
+	@mkdir -p tests
+	@if [ ! -f $(UT_SRC) ]; then \
+		echo "Error: tests not found"; \
+		exit 1; \
+	fi
+	$(CC) -o $(UT_NAME) $(UT_SRC) $(UT_FLAGS)
+	./unit_tests
 
 coverage: tests_run
-	gcovr
+	gcovr --exclude test/
 	@find -name "*.gcda" -delete -o -name "*.gcno" -delete
-	@find -name "unit_tests"	-delete
+	@find -name $(UT_NAME) -delete
 
-coding_style:
+coding_style: fclean
 	coding-style . .
 	@cat coding-style-reports.log
-	@rm -f "coding-style-reports.log";
+	@$(RM) -f "coding-style-reports.log";
+
+.PHONY: all				\
+		re				\
+		fclean			\
+		clean			\
+		tests_run 		\
+		coverage 		\
+		coding_style	\
+		final_check
